body:
  - type: input
    id: stream_id
    attributes:
      label: Stream ID (required)
      description: Unique ID of the channel and feed from [iptv-org.github.io](https://iptv-org.github.io/). If you cannot find the channel or feed you are looking for in the list, please let us know via one of the [forms](https://github.com/iptv-org/database/issues/new/choose) before posting your request.
      placeholder: 'BBCAmerica.us@HD'
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: 'Any additional information that may help find a link to the stream faster?'

  - type: markdown
    attributes:
      value: |
        ⚠️ **IMPORTANT:** Requests without a valid stream ID will be closed immediately.